apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: zero-downtime
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/appdb"
  ADMIN_TOKEN: "f3c9a1d5-89b2-4d7c-9304-4b486b8c47d2"
