apiVersion: v1
kind: Pod
metadata:
  name: test-unsigned
  namespace: zero-downtime
spec:
  imagePullSecrets:
  - name: ghcr-secret
  containers:
  - name: test
    image: ghcr.io/sheshagiri-62/myapp:1.8.0-noisytest
